#!/usr/bin/env bash
# Build "LazyScale Console.app" — a double-clickable launcher for the console.
#
#   ./mac/make-app.sh
#
# The app is a thin wrapper, not a copy: it starts run-local.sh from wherever
# this repository lives and opens /app in the default browser. Pull the repo and
# the app is up to date; there is no second copy of the code to go stale.
#
# Installs to ~/Applications by default (no admin password needed).
#   DEST=/Applications ./mac/make-app.sh   to install for everyone.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${DEST:-$HOME/Applications}"
APP="$DEST/LazyScale Console.app"
NAME="LazyScale Console"

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$NAME</string>
  <key>CFBundleDisplayName</key><string>$NAME</string>
  <key>CFBundleIdentifier</key><string>com.lazyscale.console</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <!-- No Dock icon bouncing around after the browser opens; this is a launcher,
       not an application with windows of its own. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST

# ── icon, from the square logo already in brand/ ─────────────────────────────
if [ -f "$REPO/brand/logo-square.png" ] && command -v iconutil >/dev/null 2>&1; then
  ICONSET="$(mktemp -d)/icon.iconset"
  mkdir -p "$ICONSET"
  for s in 16 32 64 128 256 512; do
    sips -z $s $s "$REPO/brand/logo-square.png" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null 2>&1
    d=$((s * 2))
    sips -z $d $d "$REPO/brand/logo-square.png" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null 2>&1
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/icon.icns" 2>/dev/null || true
  rm -rf "$(dirname "$ICONSET")"
fi

# ── the launcher ─────────────────────────────────────────────────────────────
cat > "$APP/Contents/MacOS/launch" <<LAUNCH
#!/usr/bin/env bash
# Generated by mac/make-app.sh. Edit that, not this.
set -uo pipefail

REPO="$REPO"
PORT="\${PORT:-3100}"
LOG="\$HOME/Library/Logs/LazyScale-Console.log"
mkdir -p "\$(dirname "\$LOG")"

note() {
  osascript -e "display notification \"\$2\" with title \"LazyScale Console\"" >/dev/null 2>&1 || true
  echo "\$(date '+%F %T') \$1: \$2" >> "\$LOG"
}

if [ ! -d "\$REPO" ]; then
  osascript -e 'display alert "LazyScale Console" message "The project folder has moved. Run ./mac/make-app.sh again from its new location."' >/dev/null 2>&1
  exit 1
fi

# Already running? Just open it. Starting a second server would fail on the port
# and look like a crash.
if curl -s -m 2 -o /dev/null "http://localhost:\$PORT/"; then
  open "http://localhost:\$PORT/app"
  exit 0
fi

# A GUI app inherits almost no PATH, so node and vercel installed by Homebrew or
# nvm are invisible unless we go looking for them.
export PATH="/opt/homebrew/bin:/usr/local/bin:\$HOME/.npm-global/bin:\$PATH"
if [ -s "\$HOME/.nvm/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "\$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true
fi

if ! command -v vercel >/dev/null 2>&1; then
  osascript -e 'display alert "LazyScale Console" message "The Vercel CLI was not found. Open Terminal and run:    npm install -g vercel"' >/dev/null 2>&1
  note error "vercel CLI not on PATH"
  exit 1
fi

note start "Starting the server…"
cd "\$REPO" || exit 1

# macOS gates an app bundle's access to Downloads, Documents and Desktop. An
# unsigned launcher gets "Operation not permitted" rather than a prompt, so say
# what to click instead of failing into a log nobody opens.
if [ ! -r "\$REPO/run-local.sh" ] || ! /bin/test -x "\$REPO/run-local.sh"; then
  osascript -e 'display alert "LazyScale Console" message "macOS is blocking access to the project folder.\n\nSystem Settings > Privacy & Security > Files and Folders > LazyScale Console, and switch on the folder the project is in.\n\nOr use the Terminal launcher: mac/LazyScale Console.command" as critical' >/dev/null 2>&1
  note error "TCC blocked access to \$REPO"
  exit 1
fi

./run-local.sh >> "\$LOG" 2>&1 &
SERVER=\$!

# The check above passes on permissions but the exec can still be refused;
# catch that too rather than waiting sixty seconds for a server that never ran.
sleep 2
if ! kill -0 \$SERVER 2>/dev/null && ! curl -s -m 2 -o /dev/null "http://localhost:\$PORT/"; then
  if grep -q "Operation not permitted" "\$LOG" 2>/dev/null; then
    osascript -e 'display alert "LazyScale Console" message "macOS blocked the launcher from reading the project folder.\n\nSystem Settings > Privacy & Security > Files and Folders, find LazyScale Console, and switch on the folder the project is in.\n\nOr use mac/LazyScale Console.command, which runs in Terminal." as critical' >/dev/null 2>&1
    exit 1
  fi
fi

# Wait for it to answer, then open the console. 60s is generous; the first run
# of vercel dev resolves the linked project and is slower than the rest.
for _ in \$(seq 1 60); do
  if curl -s -m 2 -o /dev/null "http://localhost:\$PORT/"; then
    open "http://localhost:\$PORT/app"
    wait \$SERVER
    exit 0
  fi
  if ! kill -0 \$SERVER 2>/dev/null; then
    osascript -e 'display alert "LazyScale Console" message "The server stopped while starting. See ~/Library/Logs/LazyScale-Console.log"' >/dev/null 2>&1
    exit 1
  fi
  sleep 1
done

osascript -e 'display alert "LazyScale Console" message "The server did not answer within 60 seconds. See ~/Library/Logs/LazyScale-Console.log"' >/dev/null 2>&1
kill \$SERVER 2>/dev/null
exit 1
LAUNCH

chmod +x "$APP/Contents/MacOS/launch"

# Gatekeeper treats a freshly written bundle as unsigned-but-local; clearing any
# quarantine flag avoids the "cannot be opened" dialog on first launch.
xattr -cr "$APP" 2>/dev/null || true
touch "$APP"

echo "Built: $APP"
echo "Open it from Spotlight, or: open -a \"$NAME\""
